apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o ../ckan-docker-to-kubes/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ckan-dev
  name: ckan-dev
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: ckan-dev
