apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o ../ckan-docker-to-kubes/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: datapusher
  name: datapusher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datapusher
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml -o ../ckan-docker-to-kubes/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: datapusher
    spec:
      containers:
        - image: ckan/ckan-base-datapusher:0.0.19
          livenessProbe:
            httpGet:
              path: /
              port: 8800
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          name: datapusher
      restartPolicy: Always
