apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: datapusher
  name: datapusher
spec:
  ports:
    - name: "8800"
      port: 8800
      targetPort: 8800
  selector:
    io.kompose.service: datapusher
