apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "81"
      port: 81
      targetPort: 80
    - name: "8443"
      port: 8443
      targetPort: 443
  selector:
    io.kompose.service: nginx
