apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o ../ckan-docker-to-kubes/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.dev.yml -o ../ckan-docker-to-kubes/
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/nginx/certs
              name: nginx-certs
            - mountPath: /var/cache/nginx
              name: nginx-cache
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-config
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - name: nginx-certs
          persistentVolumeClaim:
            claimName: nginx-certs
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-config
          configMap:
            name: nginx-config
