apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.dev.yml -o ../ckan-docker-to-kubes/
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
    - name: "81"
      port: 81
      targetPort: 80
    - name: "8443"
      port: 8443
      targetPort: 443
  selector:
    io.kompose.service: nginx
