apiVersion: v1
items:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      labels:
        io.kompose.service: ckan-dev
        pod-template-hash: 5d54478c9c
      name: ckan-service
    spec:
      host: ckan-service-buspark-test-dev.apps.rm3.7wse.p1.openshiftapps.com
      port:
        targetPort: 5000
      to:
        kind: Service
        name: ckan-service
        weight: 100
      wildcardPolicy: None
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        openshift.io/host.generated: "true"
      labels:
        io.kompose.service: nginx
      name: nginx
    spec:
      host: nginx-buspark-test-dev.apps.rm3.7wse.p1.openshiftapps.com
      port:
        targetPort: 81
      to:
        kind: Service
        name: nginx
        weight: 100
      wildcardPolicy: None
kind: List
metadata:
